/* eslint-disable @typescript-eslint/no-explicit-any */

const img = (id: string, w = 800, h = 600) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;
const avatar = (n: number) => `https://i.pravatar.cc/300?img=${n}`;

const BAN: Record<string, string> = {
  builders:       '1503387762-592deb58ef4e',
  plumbers:       '1607472586893-edb57bdc0e39',
  electricians:   '1558618666-fcd25c85cd64',
  painters:       '1562259949-e8e7689d7828',
  landscape:      '1416879595882-3373a0480b5b',
  hvac:           '1631545308180-6b7e5b4b0e8e',
  roofers:        '1632823469850-1f7e5b5b0e8e',
  carpenters:     '1572297479647-c39e6f0b3e2a',
  handyman:       '1581244277943-fe4a9c777189',
  cleaners:       '1581578731548-c64695cc6952',
  general:        '1503387762-592deb58ef4e',
};

const bannerFor = (category: string) => img(BAN[category] || BAN.general, 1200, 500);

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

const B64_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const b64url = (s: string) => {
  let out = '';
  for (let i = 0; i < s.length; i += 3) {
    const c1 = s.charCodeAt(i);
    const c2 = i + 1 < s.length ? s.charCodeAt(i + 1) : 0;
    const c3 = i + 2 < s.length ? s.charCodeAt(i + 2) : 0;
    const e1 = c1 >> 2;
    const e2 = ((c1 & 3) << 4) | (c2 >> 4);
    const e3 = ((c2 & 15) << 2) | (c3 >> 6);
    const e4 = c3 & 63;
    out += B64_CHARS[e1] + B64_CHARS[e2];
    out += i + 1 < s.length ? B64_CHARS[e3] : '';
    out += i + 2 < s.length ? B64_CHARS[e4] : '';
  }
  return out.replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
};
const buildDemoJwt = (payload: any) => {
  const header = b64url(JSON.stringify({ alg: 'none', typ: 'JWT' }));
  const body = b64url(JSON.stringify(payload));
  return `${header}.${body}.demo-signature-not-verified`;
};

export const generateDemoToken = (userId: string, role: 'user' | 'contractor' = 'user', email: string = 'demo@ratedeed.com') => {
  const exp = Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 30;
  return buildDemoJwt({ id: userId, _id: userId, role, emailVerified: true, exp, iat: Math.floor(Date.now() / 1000) });
};

const hoursAgo = (n: number) => {
  const d = new Date();
  d.setHours(d.getHours() - n);
  return d.toISOString();
};

export const DEMO_ZIP = '94110';

export const DEMO_USER_ID = 'demo-user-1';
export const DEMO_CONTRACTOR_ID = 'demo-contractor-1';
export const DEMO_CONTRACTOR_2_ID = 'demo-contractor-2';

export const demoUser = {
  _id: DEMO_USER_ID,
  id: DEMO_USER_ID,
  firstName: 'Alex',
  lastName: 'Morgan',
  email: 'alex@demo.ratedeed.com',
  role: 'user',
  profilePicture: avatar(12),
  address: '482 Maple Street, San Francisco, CA 94110',
  zipCode: DEMO_ZIP,
  createdAt: daysAgo(120),
  phone: '415-555-0182',
  referralCode: 'ALEX2024',
  referralPoints: 150,
};

export const demoContractorUser = {
  _id: DEMO_CONTRACTOR_2_ID,
  id: DEMO_CONTRACTOR_2_ID,
  firstName: 'Marcus',
  lastName: 'Rivera',
  email: 'marcus@bluecollarpro.com',
  role: 'contractor',
  companyName: 'Blue Collar Pro Builders',
  profilePicture: avatar(33),
  address: '1820 Industrial Way, San Francisco, CA 94103',
  zipCode: '94103',
  createdAt: daysAgo(420),
  phone: '415-555-0291',
};

const baseUserBlock = (c: { firstName: string; lastName: string; profilePicture?: string; zipCode: string; companyName?: string; userId?: string }) => ({
  _id: c.userId || `user-${c.firstName.toLowerCase()}`,
  firstName: c.firstName,
  lastName: c.lastName,
  profilePicture: c.profilePicture,
  email: `${c.firstName.toLowerCase()}@demo.ratedeed.com`,
  createdAt: daysAgo(200),
  companyName: c.companyName,
  zipCode: c.zipCode,
});

export const demoContractors: any[] = [
  {
    _id: 'contractor-1',
    userId: 'user-sarah',
    companyName: 'Cornerstone Construction Co.',
    businessName: 'Cornerstone Construction Co.',
    slug: 'cornerstone-construction-co',
    category: 'builders',
    description: 'Licensed general contractors specializing in custom home builds, major renovations, and kitchen/bathroom remodels. 18 years serving the Bay Area with a focus on quality craftsmanship and on-time delivery.',
    bio: 'Family-owned and operated since 2006.',
    pricing: '$$$',
    pricingInfo: 'Premium tier, project-based quotes',
    priceRange: '$$$',
    averageRating: 4.9,
    reviewCount: 127,
    numReviews: 127,
    isVerified: true,
    isTopRated: true,
    isSponsored: true,
    licenseStatus: 'Verified',
    licenseNumber: 'B-1234567',
    yearsExperience: 18,
    responseTimeMinutes: 35,
    avgResponseHours: 0.6,
    distance: '2.1 mi',
    zipCodesCovered: ['94110', '94103', '94114', '94117', '94131'],
    zipCode: '94110',
    businessAddress: '482 Construction Ave, San Francisco, CA 94110',
    contactInfo: {
      phoneNumber: '415-555-0101',
      email: 'sarah@cornerstone.demo',
      website: 'cornerstone.demo',
      streetAddress: '482 Construction Ave, San Francisco, CA 94110',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94110',
    },
    phone: '415-555-0101',
    email: 'sarah@cornerstone.demo',
    website: 'cornerstone.demo',
    profilePicture: avatar(47),
    bannerImage: bannerFor('builders'),
    bannerUrl: bannerFor('builders'),
    bannerImages: [bannerFor('builders')],
    servicesOffered: [
      { name: 'Custom Home Building', description: 'Ground-up construction of single-family homes', priceRange: '$500,000 – $2M+' },
      { name: 'Kitchen Remodel', description: 'Full kitchen renovations including cabinets, countertops, and appliances', priceRange: '$45,000 – $120,000' },
      { name: 'Bathroom Remodel', description: 'Master and secondary bathroom renovations', priceRange: '$25,000 – $75,000' },
      { name: 'Home Additions', description: 'Room additions, second-story additions, and ADUs', priceRange: '$150,000 – $400,000' },
    ],
    portfolio: [
      { _id: 'p-1', name: 'Modern Mission District Home', description: '3,200 sqft new build with rooftop deck', imageUrl: img('1503387762-592deb58ef4e'), images: [img('1503387762-592deb58ef4e')] },
      { _id: 'p-2', name: 'Noe Valley Kitchen Remodel', description: 'Complete kitchen gut renovation', imageUrl: img('1556909114-f6e7ad7d3136'), images: [img('1556909114-f6e7ad7d3136')] },
      { _id: 'p-3', name: 'Bernal Heights Master Suite', description: 'Top-floor master suite addition', imageUrl: img('1600585154340-be6161a56a0c'), images: [img('1600585154340-be6161a56a0c')] },
    ],
    certifications: ['CSLB Licensed', 'EPA Lead-Safe Certified', 'BBB A+ Rating'],
    businessHours: {
      monday: { open: '07:00', close: '17:00', isOpen: true },
      tuesday: { open: '07:00', close: '17:00', isOpen: true },
      wednesday: { open: '07:00', close: '17:00', isOpen: true },
      thursday: { open: '07:00', close: '17:00', isOpen: true },
      friday: { open: '07:00', close: '17:00', isOpen: true },
      saturday: { open: '09:00', close: '14:00', isOpen: true },
      sunday: { open: '', close: '', isOpen: false },
    },
    user: baseUserBlock({ firstName: 'Sarah', lastName: 'Chen', profilePicture: avatar(47), zipCode: '94110', companyName: 'Cornerstone Construction Co.', userId: 'user-sarah' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-2',
    userId: 'user-mike',
    companyName: 'RapidFlow Plumbing',
    businessName: 'RapidFlow Plumbing',
    slug: 'rapidflow-plumbing',
    category: 'plumbers',
    description: '24/7 emergency plumbing service. Drain cleaning, leak repair, water heater installation, and full re-pipes. Licensed, bonded, insured. Same-day service available.',
    pricing: '$$',
    pricingInfo: 'Mid-range, hourly + flat-rate options',
    priceRange: '$$',
    averageRating: 4.8,
    reviewCount: 89,
    numReviews: 89,
    isVerified: true,
    isTopRated: true,
    licenseStatus: 'Verified',
    licenseNumber: 'C-36-987654',
    yearsExperience: 12,
    responseTimeMinutes: 20,
    avgResponseHours: 0.3,
    distance: '3.4 mi',
    zipCodesCovered: ['94110', '94103', '94114', '94117', '94131', '94121', '94109'],
    zipCode: '94110',
    businessAddress: '1200 Plumbing Way, San Francisco, CA 94103',
    contactInfo: {
      phoneNumber: '415-555-0202',
      email: 'mike@rapidflow.demo',
      website: 'rapidflow.demo',
      streetAddress: '1200 Plumbing Way, San Francisco, CA 94103',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94103',
    },
    phone: '415-555-0202',
    email: 'mike@rapidflow.demo',
    website: 'rapidflow.demo',
    profilePicture: avatar(60),
    bannerImage: bannerFor('plumbers'),
    bannerUrl: bannerFor('plumbers'),
    bannerImages: [bannerFor('plumbers')],
    servicesOffered: [
      { name: 'Drain Cleaning', description: 'Snake and hydrojet drain clearing', priceRange: '$150 – $450' },
      { name: 'Water Heater Install', description: 'Tank and tankless water heater installation', priceRange: '$1,800 – $4,500' },
      { name: 'Leak Detection & Repair', description: 'Slab leaks, pipe leaks, fixture leaks', priceRange: '$200 – $2,000' },
      { name: 'Emergency Service', description: '24/7 response for burst pipes and major leaks', priceRange: '$250 – $1,500' },
    ],
    portfolio: [
      { _id: 'p-4', name: 'Tankless Water Heater Upgrade', description: 'Rinnai RU199iN installation', imageUrl: img('1607472586893-edb57bdc0e39'), images: [img('1607472586893-edb57bdc0e39')] },
      { _id: 'p-5', name: 'Bathroom Fixture Replacement', description: 'Modern faucets and shower trim', imageUrl: img('1620626011761-bfbe8e303abe'), images: [img('1620626011761-bfbe8e303abe')] },
    ],
    certifications: ['CSLB C-36 Plumbing', 'Backflow Certified', 'Watersense Partner'],
    businessHours: {
      monday: { open: '00:00', close: '23:59', isOpen: true },
      tuesday: { open: '00:00', close: '23:59', isOpen: true },
      wednesday: { open: '00:00', close: '23:59', isOpen: true },
      thursday: { open: '00:00', close: '23:59', isOpen: true },
      friday: { open: '00:00', close: '23:59', isOpen: true },
      saturday: { open: '00:00', close: '23:59', isOpen: true },
      sunday: { open: '00:00', close: '23:59', isOpen: true },
    },
    user: baseUserBlock({ firstName: 'Mike', lastName: 'Rodriguez', profilePicture: avatar(60), zipCode: '94103', companyName: 'RapidFlow Plumbing', userId: 'user-mike' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-3',
    userId: 'user-jennifer',
    companyName: 'Spark Electric Co.',
    businessName: 'Spark Electric Co.',
    slug: 'spark-electric-co',
    category: 'electricians',
    description: 'Residential and commercial electrical contractor. Panel upgrades, EV charger installs, smart home wiring, and code compliance. Free estimates on all jobs.',
    pricing: '$$',
    pricingInfo: 'Mid-range',
    priceRange: '$$',
    averageRating: 4.9,
    reviewCount: 64,
    numReviews: 64,
    isVerified: true,
    isTopRated: true,
    licenseStatus: 'Verified',
    licenseNumber: 'C-10-456789',
    yearsExperience: 15,
    responseTimeMinutes: 45,
    avgResponseHours: 0.75,
    distance: '4.2 mi',
    zipCodesCovered: ['94110', '94103', '94114', '94117', '94131', '94121', '94109', '94102'],
    zipCode: '94110',
    businessAddress: '300 Volt Lane, San Francisco, CA 94114',
    contactInfo: {
      phoneNumber: '415-555-0303',
      email: 'jennifer@sparkelectric.demo',
      website: 'sparkelectric.demo',
      streetAddress: '300 Volt Lane, San Francisco, CA 94114',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94114',
    },
    phone: '415-555-0303',
    email: 'jennifer@sparkelectric.demo',
    website: 'sparkelectric.demo',
    profilePicture: avatar(45),
    bannerImage: bannerFor('electricians'),
    bannerUrl: bannerFor('electricians'),
    bannerImages: [bannerFor('electricians')],
    servicesOffered: [
      { name: 'Panel Upgrade', description: '100A to 200A service panel upgrades', priceRange: '$3,500 – $7,500' },
      { name: 'EV Charger Install', description: 'Level 2 home EV charger installation', priceRange: '$1,200 – $2,800' },
      { name: 'Recessed Lighting', description: 'LED recessed lighting installation', priceRange: '$180 – $350 per fixture' },
      { name: 'Smart Home Wiring', description: 'Whole-home smart wiring for automation', priceRange: '$8,000 – $25,000' },
    ],
    portfolio: [
      { _id: 'p-6', name: 'Tesla Wall Connector Install', description: 'Garage EV charger with dedicated 60A circuit', imageUrl: img('1558618666-fcd25c85cd64'), images: [img('1558618666-fcd25c85cd64')] },
      { _id: 'p-7', name: 'Recessed Lighting Retrofit', description: 'Whole-home LED conversion', imageUrl: img('1565538810643-b5bdb714032a'), images: [img('1565538810643-b5bdb714032a')] },
    ],
    certifications: ['CSLB C-10 Electrical', 'Tesla Certified Installer', 'NABCEP Solar Associate'],
    businessHours: {
      monday: { open: '07:00', close: '18:00', isOpen: true },
      tuesday: { open: '07:00', close: '18:00', isOpen: true },
      wednesday: { open: '07:00', close: '18:00', isOpen: true },
      thursday: { open: '07:00', close: '18:00', isOpen: true },
      friday: { open: '07:00', close: '18:00', isOpen: true },
      saturday: { open: '09:00', close: '15:00', isOpen: true },
      sunday: { open: '', close: '', isOpen: false },
    },
    user: baseUserBlock({ firstName: 'Jennifer', lastName: 'Park', profilePicture: avatar(45), zipCode: '94114', companyName: 'Spark Electric Co.', userId: 'user-jennifer' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-4',
    userId: 'user-david',
    companyName: 'Brushwork Painting',
    businessName: 'Brushwork Painting',
    slug: 'brushwork-painting',
    category: 'painters',
    description: 'Premium interior and exterior painting. Cabinet refinishing, deck staining, and color consultation. Benjamin Moore and Sherwin-Williams certified installers.',
    pricing: '$$',
    pricingInfo: 'Mid-range',
    priceRange: '$$',
    averageRating: 4.7,
    reviewCount: 52,
    numReviews: 52,
    isVerified: true,
    isTopRated: false,
    licenseStatus: 'Verified',
    licenseNumber: 'C-33-321987',
    yearsExperience: 8,
    responseTimeMinutes: 60,
    avgResponseHours: 1,
    distance: '5.0 mi',
    zipCodesCovered: ['94110', '94114', '94117', '94131', '94121'],
    zipCode: '94110',
    businessAddress: '742 Color Court, San Francisco, CA 94117',
    contactInfo: {
      phoneNumber: '415-555-0404',
      email: 'david@brushwork.demo',
      website: 'brushwork.demo',
      streetAddress: '742 Color Court, San Francisco, CA 94117',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94117',
    },
    phone: '415-555-0404',
    email: 'david@brushwork.demo',
    website: 'brushwork.demo',
    profilePicture: avatar(15),
    bannerImage: bannerFor('painters'),
    bannerUrl: bannerFor('painters'),
    bannerImages: [bannerFor('painters')],
    servicesOffered: [
      { name: 'Interior Painting', description: 'Walls, ceilings, trim, and doors', priceRange: '$3,500 – $12,000' },
      { name: 'Exterior Painting', description: 'Full exterior repaint with prep and primer', priceRange: '$6,000 – $22,000' },
      { name: 'Cabinet Refinishing', description: 'Professional cabinet painting and refinishing', priceRange: '$5,500 – $14,000' },
      { name: 'Color Consultation', description: 'In-home color consultation with designer', priceRange: '$250 – $500' },
    ],
    portfolio: [
      { _id: 'p-8', name: 'Pacific Heights Victorian', description: '5-color exterior restoration', imageUrl: img('1562259949-e8e7689d7828'), images: [img('1562259949-e8e7689d7828')] },
      { _id: 'p-9', name: 'Modern Loft Cabinets', description: 'Dark navy cabinet refinish with brass hardware', imageUrl: img('1556909114-f6e7ad7d3136'), images: [img('1556909114-f6e7ad7d3136')] },
    ],
    certifications: ['Benjamin Moore Certified', 'Sherwin-Williams Preferred', 'EPA Lead-Safe Certified'],
    user: baseUserBlock({ firstName: 'David', lastName: 'Kim', profilePicture: avatar(15), zipCode: '94117', companyName: 'Brushwork Painting', userId: 'user-david' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-5',
    userId: 'user-olivia',
    companyName: 'GreenScape Landscaping',
    businessName: 'GreenScape Landscaping',
    slug: 'greenscape-landscaping',
    category: 'landscape',
    description: 'Full-service landscape design and installation. Drought-tolerant gardens, native plants, hardscaping, and drip irrigation. Sustainable practices since day one.',
    pricing: '$$',
    pricingInfo: 'Mid-range',
    priceRange: '$$',
    averageRating: 4.8,
    reviewCount: 41,
    numReviews: 41,
    isVerified: true,
    isTopRated: true,
    licenseStatus: 'Verified',
    licenseNumber: 'C-27-654321',
    yearsExperience: 10,
    responseTimeMinutes: 90,
    avgResponseHours: 1.5,
    distance: '6.1 mi',
    zipCodesCovered: ['94110', '94103', '94114', '94117', '94131', '94121', '94127'],
    zipCode: '94110',
    businessAddress: '85 Garden Grove, San Francisco, CA 94131',
    contactInfo: {
      phoneNumber: '415-555-0505',
      email: 'olivia@greenscape.demo',
      website: 'greenscape.demo',
      streetAddress: '85 Garden Grove, San Francisco, CA 94131',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94131',
    },
    phone: '415-555-0505',
    email: 'olivia@greenscape.demo',
    website: 'greenscape.demo',
    profilePicture: avatar(26),
    bannerImage: bannerFor('landscape'),
    bannerUrl: bannerFor('landscape'),
    bannerImages: [bannerFor('landscape')],
    servicesOffered: [
      { name: 'Landscape Design', description: 'Custom landscape design with 3D renderings', priceRange: '$2,500 – $8,000' },
      { name: 'Drought-Tolerant Gardens', description: 'California native and drought-tolerant installations', priceRange: '$5,000 – $25,000' },
      { name: 'Hardscaping', description: 'Patios, walkways, retaining walls, and outdoor kitchens', priceRange: '$8,000 – $60,000' },
      { name: 'Drip Irrigation', description: 'Smart irrigation system installation', priceRange: '$2,000 – $6,500' },
    ],
    portfolio: [
      { _id: 'p-10', name: 'Bernal Heights Hillside', description: 'Drought-tolerant terraced garden', imageUrl: img('1416879595882-3373a0480b5b'), images: [img('1416879595882-3373a0480b5b')] },
      { _id: 'p-11', name: 'Sunset District Backyard', description: 'Outdoor kitchen with pergola', imageUrl: img('1600585154340-be6161a56a0c'), images: [img('1600585154340-be6161a56a0c')] },
    ],
    certifications: ['CLCA Certified', 'Bay-Friendly Landscaping', 'QWEL Certified'],
    user: baseUserBlock({ firstName: 'Olivia', lastName: 'Martinez', profilePicture: avatar(26), zipCode: '94131', companyName: 'GreenScape Landscaping', userId: 'user-olivia' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-6',
    userId: 'user-tom',
    companyName: 'Arctic Air HVAC',
    businessName: 'Arctic Air HVAC',
    slug: 'arctic-air-hvac',
    category: 'hvac',
    description: 'Heating, ventilation, and air conditioning experts. AC installation and repair, furnace service, ductwork, and indoor air quality solutions. Energy-efficient upgrades.',
    pricing: '$$$',
    pricingInfo: 'Premium tier',
    priceRange: '$$$',
    averageRating: 4.6,
    reviewCount: 38,
    numReviews: 38,
    isVerified: true,
    isTopRated: false,
    licenseStatus: 'Verified',
    licenseNumber: 'C-20-789012',
    yearsExperience: 14,
    responseTimeMinutes: 50,
    avgResponseHours: 0.85,
    distance: '4.8 mi',
    zipCodesCovered: ['94110', '94103', '94114', '94117', '94131', '94121'],
    zipCode: '94110',
    businessAddress: '900 Cool Circle, San Francisco, CA 94103',
    contactInfo: {
      phoneNumber: '415-555-0606',
      email: 'tom@arcticair.demo',
      website: 'arcticair.demo',
      streetAddress: '900 Cool Circle, San Francisco, CA 94103',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94103',
    },
    phone: '415-555-0606',
    email: 'tom@arcticair.demo',
    website: 'arcticair.demo',
    profilePicture: avatar(52),
    bannerImage: bannerFor('hvac'),
    bannerUrl: bannerFor('hvac'),
    bannerImages: [bannerFor('hvac')],
    servicesOffered: [
      { name: 'AC Installation', description: 'Central AC and heat pump installation', priceRange: '$5,500 – $14,000' },
      { name: 'Furnace Service', description: 'Furnace repair, tune-ups, and replacement', priceRange: '$200 – $8,000' },
      { name: 'Duct Cleaning', description: 'Whole-home duct cleaning and sanitizing', priceRange: '$450 – $900' },
      { name: 'Indoor Air Quality', description: 'Air purifiers, humidifiers, and filtration', priceRange: '$800 – $4,500' },
    ],
    portfolio: [
      { _id: 'p-12', name: 'Mission District Duct Retrofit', description: 'Complete duct system redesign', imageUrl: img('1631545308180-6b7e5b4b0e8e'), images: [img('1631545308180-6b7e5b4b0e8e')] },
    ],
    certifications: ['NATE Certified', 'EPA 608 Universal', 'Energy Star Partner'],
    user: baseUserBlock({ firstName: 'Tom', lastName: 'Wilson', profilePicture: avatar(52), zipCode: '94103', companyName: 'Arctic Air HVAC', userId: 'user-tom' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-7',
    userId: 'user-roberto',
    companyName: 'Summit Roofing Solutions',
    businessName: 'Summit Roofing Solutions',
    slug: 'summit-roofing-solutions',
    category: 'roofers',
    description: 'Residential and commercial roofing. Asphalt shingles, metal roofing, flat roof systems, and storm damage repair. GAF Master Elite certified.',
    pricing: '$$$',
    pricingInfo: 'Premium tier',
    priceRange: '$$$',
    averageRating: 4.9,
    reviewCount: 73,
    numReviews: 73,
    isVerified: true,
    isTopRated: true,
    licenseStatus: 'Verified',
    licenseNumber: 'C-39-345678',
    yearsExperience: 22,
    responseTimeMinutes: 40,
    avgResponseHours: 0.7,
    distance: '7.2 mi',
    zipCodesCovered: ['94110', '94103', '94114', '94117', '94131', '94121', '94109', '94102', '94115'],
    zipCode: '94110',
    businessAddress: '1500 Ridge Road, San Francisco, CA 94131',
    contactInfo: {
      phoneNumber: '415-555-0707',
      email: 'roberto@summitroofing.demo',
      website: 'summitroofing.demo',
      streetAddress: '1500 Ridge Road, San Francisco, CA 94131',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94131',
    },
    phone: '415-555-0707',
    email: 'roberto@summitroofing.demo',
    website: 'summitroofing.demo',
    profilePicture: avatar(11),
    bannerImage: bannerFor('roofers'),
    bannerUrl: bannerFor('roofers'),
    bannerImages: [bannerFor('roofers')],
    servicesOffered: [
      { name: 'Roof Replacement', description: 'Complete tear-off and replacement', priceRange: '$12,000 – $45,000' },
      { name: 'Roof Repair', description: 'Leak repair, shingle replacement, flashing', priceRange: '$350 – $3,500' },
      { name: 'Gutter Installation', description: 'Seamless aluminum gutter installation', priceRange: '$1,500 – $4,500' },
      { name: 'Storm Damage Repair', description: 'Emergency storm damage and insurance claim assistance', priceRange: '$1,000 – $25,000' },
    ],
    portfolio: [
      { _id: 'p-13', name: 'Twin Peaks Estate', description: 'Complete standing seam metal roof', imageUrl: img('1632823469850-1f7e5b5b0e8e'), images: [img('1632823469850-1f7e5b5b0e8e')] },
      { _id: 'p-14', name: 'Marina District Flat Roof', description: 'TPO membrane commercial flat roof', imageUrl: img('1631545308180-6b7e5b4b0e8e'), images: [img('1631545308180-6b7e5b4b0e8e')] },
    ],
    certifications: ['GAF Master Elite', 'CertainTeed SELECT', 'BBB A+ Rating'],
    user: baseUserBlock({ firstName: 'Roberto', lastName: 'Santos', profilePicture: avatar(11), zipCode: '94131', companyName: 'Summit Roofing Solutions', userId: 'user-roberto' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-8',
    userId: 'user-anna',
    companyName: 'Blue Collar Pro Builders',
    businessName: 'Blue Collar Pro Builders',
    slug: 'blue-collar-pro-builders',
    category: 'handyman',
    description: 'Your go-to handyman service. Drywall repair, fixture replacement, door and window repairs, TV mounting, and general home maintenance. One trip, one price.',
    pricing: '$',
    pricingInfo: 'Budget-friendly',
    priceRange: '$',
    averageRating: 4.8,
    reviewCount: 156,
    numReviews: 156,
    isVerified: true,
    isTopRated: true,
    licenseStatus: 'Verified',
    licenseNumber: 'B-9876543',
    yearsExperience: 6,
    responseTimeMinutes: 25,
    avgResponseHours: 0.4,
    distance: '1.8 mi',
    zipCodesCovered: ['94110', '94103', '94114', '94117', '94131', '94121', '94109', '94102', '94115', '94123'],
    zipCode: '94110',
    businessAddress: '1820 Industrial Way, San Francisco, CA 94103',
    contactInfo: {
      phoneNumber: '415-555-0808',
      email: 'marcus@bluecollarpro.demo',
      website: 'bluecollarpro.demo',
      streetAddress: '1820 Industrial Way, San Francisco, CA 94103',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94103',
    },
    phone: '415-555-0808',
    email: 'marcus@bluecollarpro.demo',
    website: 'bluecollarpro.demo',
    profilePicture: avatar(33),
    bannerImage: bannerFor('handyman'),
    bannerUrl: bannerFor('handyman'),
    bannerImages: [bannerFor('handyman')],
    servicesOffered: [
      { name: 'Drywall Repair', description: 'Holes, cracks, water damage repair', priceRange: '$150 – $650' },
      { name: 'TV Mounting', description: 'TV wall mount with cable concealment', priceRange: '$180 – $450' },
      { name: 'Door & Window Repair', description: 'Sticking doors, broken locks, weatherstripping', priceRange: '$120 – $550' },
      { name: 'General Maintenance', description: 'Honey-do lists and small repairs', priceRange: '$95/hr' },
    ],
    portfolio: [
      { _id: 'p-15', name: 'TV Wall Mount Gallery', description: '75" Frame TV over fireplace', imageUrl: img('1581244277943-fe4a9c777189'), images: [img('1581244277943-fe4a9c777189')] },
      { _id: 'p-16', name: 'Bathroom Fixture Swap', description: 'Modern faucets and showerhead install', imageUrl: img('1620626011761-bfbe8e303abe'), images: [img('1620626011761-bfbe8e303abe')] },
    ],
    certifications: ['EPA Lead-Safe Certified', 'Insured & Bonded', 'Thumbtack Top Pro'],
    user: baseUserBlock({ firstName: 'Marcus', lastName: 'Rivera', profilePicture: avatar(33), zipCode: '94103', companyName: 'Blue Collar Pro Builders', userId: 'user-anna' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-9',
    userId: 'user-lisa',
    companyName: 'Crystal Clean Services',
    businessName: 'Crystal Clean Services',
    slug: 'crystal-clean-services',
    category: 'cleaners',
    description: 'Eco-friendly residential and commercial cleaning. Deep cleans, move-in/move-out, post-construction, and recurring housekeeping. Green Seal certified products.',
    pricing: '$$',
    pricingInfo: 'Mid-range',
    priceRange: '$$',
    averageRating: 4.7,
    reviewCount: 92,
    numReviews: 92,
    isVerified: true,
    isTopRated: true,
    licenseStatus: 'Verified',
    licenseNumber: 'B-5566778',
    yearsExperience: 7,
    responseTimeMinutes: 30,
    avgResponseHours: 0.5,
    distance: '3.0 mi',
    zipCodesCovered: ['94110', '94103', '94114', '94117', '94131', '94121', '94109', '94102'],
    zipCode: '94110',
    businessAddress: '320 Sparkle Street, San Francisco, CA 94114',
    contactInfo: {
      phoneNumber: '415-555-0909',
      email: 'lisa@crystalclean.demo',
      website: 'crystalclean.demo',
      streetAddress: '320 Sparkle Street, San Francisco, CA 94114',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94114',
    },
    phone: '415-555-0909',
    email: 'lisa@crystalclean.demo',
    website: 'crystalclean.demo',
    profilePicture: avatar(20),
    bannerImage: bannerFor('cleaners'),
    bannerUrl: bannerFor('cleaners'),
    bannerImages: [bannerFor('cleaners')],
    servicesOffered: [
      { name: 'Deep Cleaning', description: 'Top-to-bottom detailed cleaning', priceRange: '$280 – $650' },
      { name: 'Move In/Out Clean', description: 'Full empty-home cleaning for moves', priceRange: '$350 – $850' },
      { name: 'Recurring Housekeeping', description: 'Weekly, biweekly, or monthly cleanings', priceRange: '$140 – $280' },
      { name: 'Post-Construction', description: 'Construction dust and debris cleanup', priceRange: '$450 – $1,800' },
    ],
    portfolio: [
      { _id: 'p-17', name: 'Pacific Heights Move-Out', description: 'Complete empty-home detailing', imageUrl: img('1581578731548-c64695cc6952'), images: [img('1581578731548-c64695cc6952')] },
    ],
    certifications: ['Green Seal Certified', 'ISSA Cleaning Management', 'Insured & Bonded'],
    user: baseUserBlock({ firstName: 'Lisa', lastName: 'Thompson', profilePicture: avatar(20), zipCode: '94114', companyName: 'Crystal Clean Services', userId: 'user-lisa' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-10',
    userId: 'user-james',
    companyName: 'Heritage Woodworks',
    businessName: 'Heritage Woodworks',
    slug: 'heritage-woodworks',
    category: 'carpenters',
    description: 'Custom millwork, cabinetry, and finish carpentry. Built-in shelving, custom desks, crown molding, and historic restoration. Master carpenter with 20+ years experience.',
    pricing: '$$$',
    pricingInfo: 'Premium tier',
    priceRange: '$$$',
    averageRating: 5.0,
    reviewCount: 31,
    numReviews: 31,
    isVerified: true,
    isTopRated: true,
    licenseStatus: 'Verified',
    licenseNumber: 'C-6-234567',
    yearsExperience: 23,
    responseTimeMinutes: 120,
    avgResponseHours: 2,
    distance: '5.5 mi',
    zipCodesCovered: ['94110', '94114', '94117', '94131', '94121', '94115'],
    zipCode: '94110',
    businessAddress: '65 Workshop Way, San Francisco, CA 94117',
    contactInfo: {
      phoneNumber: '415-555-1010',
      email: 'james@heritagewood.demo',
      website: 'heritagewood.demo',
      streetAddress: '65 Workshop Way, San Francisco, CA 94117',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94117',
    },
    phone: '415-555-1010',
    email: 'james@heritagewood.demo',
    website: 'heritagewood.demo',
    profilePicture: avatar(8),
    bannerImage: bannerFor('carpenters'),
    bannerUrl: bannerFor('carpenters'),
    bannerImages: [bannerFor('carpenters')],
    servicesOffered: [
      { name: 'Custom Cabinetry', description: 'Built-to-order cabinets for kitchens, baths, and built-ins', priceRange: '$8,000 – $45,000' },
      { name: 'Crown Molding', description: 'Custom crown molding and trim work', priceRange: '$18 – $42 per linear foot' },
      { name: 'Custom Shelving', description: 'Floor-to-ceiling built-in shelving', priceRange: '$2,500 – $12,000' },
      { name: 'Historic Restoration', description: 'Restoration of historic millwork and details', priceRange: 'Contact for quote' },
    ],
    portfolio: [
      { _id: 'p-18', name: 'Pacific Heights Library', description: 'Floor-to-ceiling walnut library', imageUrl: img('1572297479647-c39e6f0b3e2a'), images: [img('1572297479647-c39e6f0b3e2a')] },
      { _id: 'p-19', name: 'Edwardian Restoration', description: 'Restored 1908 craftsman trim', imageUrl: img('1556909114-f6e7ad7d3136'), images: [img('1556909114-f6e7ad7d3136')] },
    ],
    certifications: ['AWI Member', 'Master Carpenters Association', 'Historic Preservation Certified'],
    user: baseUserBlock({ firstName: 'James', lastName: 'Whitaker', profilePicture: avatar(8), zipCode: '94117', companyName: 'Heritage Woodworks', userId: 'user-james' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-11',
    userId: 'user-patricia',
    companyName: 'Sterling Electric',
    businessName: 'Sterling Electric',
    slug: 'sterling-electric',
    category: 'electricians',
    description: 'Boutique electrical service for homes and small businesses. Specializing in modern lighting design, generator installs, and home automation. Master electrician on every job.',
    pricing: '$$$',
    pricingInfo: 'Premium tier',
    priceRange: '$$$',
    averageRating: 4.8,
    reviewCount: 28,
    numReviews: 28,
    isVerified: true,
    isTopRated: false,
    licenseStatus: 'Verified',
    licenseNumber: 'C-10-112233',
    yearsExperience: 19,
    responseTimeMinutes: 75,
    avgResponseHours: 1.25,
    distance: '6.7 mi',
    zipCodesCovered: ['94110', '94114', '94117', '94115'],
    zipCode: '94110',
    businessAddress: '44 Ampere Alley, San Francisco, CA 94115',
    contactInfo: {
      phoneNumber: '415-555-1111',
      email: 'patricia@sterlingelectric.demo',
      website: 'sterlingelectric.demo',
      streetAddress: '44 Ampere Alley, San Francisco, CA 94115',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94115',
    },
    phone: '415-555-1111',
    email: 'patricia@sterlingelectric.demo',
    website: 'sterlingelectric.demo',
    profilePicture: avatar(31),
    bannerImage: bannerFor('electricians'),
    bannerUrl: bannerFor('electricians'),
    bannerImages: [bannerFor('electricians')],
    servicesOffered: [
      { name: 'Lighting Design', description: 'Architectural lighting design and install', priceRange: '$3,500 – $18,000' },
      { name: 'Generator Install', description: 'Whole-home backup generator systems', priceRange: '$12,000 – $32,000' },
      { name: 'Home Automation', description: 'Lutron and Control4 certified installer', priceRange: '$8,000 – $60,000' },
    ],
    certifications: ['Master Electrician', 'Lutron Gold', 'Generac Authorized Dealer'],
    user: baseUserBlock({ firstName: 'Patricia', lastName: 'Goldberg', profilePicture: avatar(31), zipCode: '94115', companyName: 'Sterling Electric', userId: 'user-patricia' }),
    onboardingComplete: true,
  },
  {
    _id: 'contractor-12',
    userId: 'user-derek',
    companyName: 'AllStar Home Services',
    businessName: 'AllStar Home Services',
    slug: 'allstar-home-services',
    category: 'handyman',
    description: 'Reliable handyman for everyday home repairs. Furniture assembly, shelving, picture hanging, and small plumbing/electrical fixes. Available weekends.',
    pricing: '$',
    pricingInfo: 'Budget-friendly',
    priceRange: '$',
    averageRating: 4.5,
    reviewCount: 47,
    numReviews: 47,
    isVerified: false,
    isTopRated: false,
    licenseStatus: 'Pending',
    licenseNumber: '',
    yearsExperience: 3,
    responseTimeMinutes: 120,
    avgResponseHours: 2,
    distance: '2.9 mi',
    zipCodesCovered: ['94110', '94103', '94114'],
    zipCode: '94110',
    businessAddress: '210 Fixit Lane, San Francisco, CA 94110',
    contactInfo: {
      phoneNumber: '415-555-1212',
      email: 'derek@allstar.demo',
      streetAddress: '210 Fixit Lane, San Francisco, CA 94110',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94110',
    },
    phone: '415-555-1212',
    email: 'derek@allstar.demo',
    profilePicture: avatar(53),
    bannerImage: bannerFor('handyman'),
    bannerUrl: bannerFor('handyman'),
    bannerImages: [bannerFor('handyman')],
    servicesOffered: [
      { name: 'Furniture Assembly', description: 'IKEA, Wayfair, and custom furniture assembly', priceRange: '$85 – $350' },
      { name: 'Picture & Mirror Hanging', description: 'Secure hanging for artwork and mirrors', priceRange: '$60 – $250' },
      { name: 'Small Repairs', description: 'Door knobs, cabinet handles, and minor fixes', priceRange: '$75 – $300' },
    ],
    certifications: ['Insured'],
    user: baseUserBlock({ firstName: 'Derek', lastName: 'Nguyen', profilePicture: avatar(53), zipCode: '94110', companyName: 'AllStar Home Services', userId: 'user-derek' }),
    onboardingComplete: true,
  },
];

export const demoReviews: any[] = [
  { _id: 'r-1', user: { _id: 'u-1', firstName: 'Megan', lastName: 'Davis', profilePicture: avatar(25) }, rating: 5, title: 'Beautiful work, on time and on budget', comment: 'Sarah and her team completely transformed our home. The new kitchen is gorgeous and the project finished exactly on the date they promised. Communication was excellent throughout. Highly recommend!', createdAt: daysAgo(14) },
  { _id: 'r-2', user: { _id: 'u-2', firstName: 'Brian', lastName: 'Hughes', profilePicture: avatar(14) }, rating: 5, title: 'Top quality craftsmanship', comment: 'We hired Cornerstone for a major home addition and couldn\'t be happier. The attention to detail was incredible, and they handled every permit issue without us having to chase anything down.', createdAt: daysAgo(32) },
  { _id: 'r-3', user: { _id: 'u-3', firstName: 'Karen', lastName: 'Mitchell', profilePicture: avatar(23) }, rating: 4, title: 'Great experience overall', comment: 'The team was professional and the work was excellent. The only reason for 4 stars instead of 5 is the project ran about a week longer than initially estimated, but the extra time was due to supply chain issues and they kept us informed throughout.', createdAt: daysAgo(48) },
  { _id: 'r-4', user: { _id: 'u-4', firstName: 'Daniel', lastName: 'Wright', profilePicture: avatar(7) }, rating: 5, title: 'Saved our renovation', comment: 'We had a previous contractor abandon our bathroom remodel halfway through. Cornerstone stepped in, assessed what was done, fixed the issues, and finished the job to a standard we\'re thrilled with. Lifesavers.', createdAt: daysAgo(67) },
  { _id: 'r-5', user: { _id: 'u-5', firstName: 'Priya', lastName: 'Sharma', profilePicture: avatar(36) }, rating: 5, title: 'Best contractor we\'ve worked with', comment: 'I\'ve worked with 4 contractors over the years on different projects. Cornerstone is hands-down the best. Clean job site, transparent billing, and the result speaks for itself.', createdAt: daysAgo(91) },

  { _id: 'r-6', user: { _id: 'u-6', firstName: 'Robert', lastName: 'Lee', profilePicture: avatar(17) }, rating: 5, title: '24/7 service that actually shows up', comment: 'Had a burst pipe at 2am and Mike was at my door within 30 minutes. Fixed the issue quickly and the price was exactly what he quoted on the phone. Saved my home from major water damage.', createdAt: daysAgo(8) },
  { _id: 'r-7', user: { _id: 'u-7', firstName: 'Susan', lastName: 'Garcia', profilePicture: avatar(44) }, rating: 5, title: 'Tankless water heater install', comment: 'Mike walked us through the options and was upfront about costs. Installation was clean and he even helped us set up the recycling program for the old unit. Great service.', createdAt: daysAgo(21) },
  { _id: 'r-8', user: { _id: 'u-8', firstName: 'Chris', lastName: 'Brown', profilePicture: avatar(9) }, rating: 4, title: 'Quick drain fix', comment: 'Cleared a stubborn kitchen drain that another plumber couldn\'t. Fair price and very professional. Will use again for sure.', createdAt: daysAgo(38) },

  { _id: 'r-9', user: { _id: 'u-9', firstName: 'Emma', lastName: 'Wilson', profilePicture: avatar(49) }, rating: 5, title: 'EV charger install done right', comment: 'Jennifer handled our Tesla charger install perfectly. Permits, panel upgrade, dedicated circuit, and a clean install in the garage. Everything works flawlessly.', createdAt: daysAgo(11) },
  { _id: 'r-10', user: { _id: 'u-10', firstName: 'Mark', lastName: 'Taylor', profilePicture: avatar(13) }, rating: 5, title: 'Reasonable rates, professional work', comment: 'We had several outlets that weren\'t working and a chandelier to install. Jennifer diagnosed the issue quickly and had everything done within 2 hours. Fair pricing, no upselling.', createdAt: daysAgo(27) },
  { _id: 'r-11', user: { _id: 'u-11', firstName: 'Aisha', lastName: 'Patel', profilePicture: avatar(24) }, rating: 5, title: 'Smart home wiring experts', comment: 'Jennifer wired our entire new construction for smart home automation. Every switch, every outlet, every scene works exactly as designed. She thought of things we never would have.', createdAt: daysAgo(55) },

  { _id: 'r-12', user: { _id: 'u-12', firstName: 'Greg', lastName: 'Anderson', profilePicture: avatar(68) }, rating: 5, title: 'Cabinets look brand new', comment: 'We thought we\'d have to replace our kitchen cabinets. David refinished them and they look better than the originals. Saved us thousands. Highly skilled team.', createdAt: daysAgo(19) },
  { _id: 'r-13', user: { _id: 'u-13', firstName: 'Linda', lastName: 'Martinez', profilePicture: avatar(32) }, rating: 4, title: 'Great exterior paint job', comment: 'David\'s team repainted our Victorian and the result is stunning. They took extra care with the historic details. Lost a star because the initial paint color was slightly off from what we ordered, but they fixed it immediately.', createdAt: daysAgo(43) },
  { _id: 'r-14', user: { _id: 'u-14', firstName: 'Tom', lastName: 'Johnson', profilePicture: avatar(58) }, rating: 5, title: 'Color consultation was worth it', comment: 'We were going to paint the house ourselves and couldn\'t decide on colors. David\'s color consultation service was a game-changer. Ended up with a palette we never would have picked but absolutely love.', createdAt: daysAgo(70) },

  { _id: 'r-15', user: { _id: 'u-15', firstName: 'Sophia', lastName: 'Nguyen', profilePicture: avatar(40) }, rating: 5, title: 'Backyard transformation', comment: 'Olivia turned our dead lawn into a gorgeous drought-tolerant garden. The design process was collaborative and the install crew was respectful of our property. Neighbors keep asking who did the work.', createdAt: daysAgo(16) },
  { _id: 'r-16', user: { _id: 'u-16', firstName: 'James', lastName: 'King', profilePicture: avatar(63) }, rating: 5, title: 'Hardscaping perfection', comment: 'Olivia designed and built a paver patio with a pergola and outdoor kitchen. Every detail was thought through. The crew cleaned up every day. We live outside now.', createdAt: daysAgo(39) },
  { _id: 'r-17', user: { _id: 'u-17', firstName: 'Maria', lastName: 'Lopez', profilePicture: avatar(50) }, rating: 4, title: 'Beautiful work, took longer than expected', comment: 'The final result is beautiful but the project took about 3 weeks longer than initially quoted. Olivia was communicative about delays (mostly weather) and didn\'t charge extra. Just plan extra time.', createdAt: daysAgo(58) },

  { _id: 'r-18', user: { _id: 'u-18', firstName: 'Andrew', lastName: 'Schultz', profilePicture: avatar(4) }, rating: 5, title: 'AC install during heatwave', comment: 'Our AC died during a 100+ degree heatwave. Tom and his crew had a new system installed within 48 hours. House has never been more comfortable. Worth every penny.', createdAt: daysAgo(12) },
  { _id: 'r-19', user: { _id: 'u-19', firstName: 'Rachel', lastName: 'Adams', profilePicture: avatar(42) }, rating: 4, title: 'Annual maintenance worth it', comment: 'We get our furnace and AC serviced yearly by Arctic Air. They always find small issues before they become big problems. Reliable and fair pricing.', createdAt: daysAgo(35) },
  { _id: 'r-20', user: { _id: 'u-20', firstName: 'Victor', lastName: 'Hernandez', profilePicture: avatar(67) }, rating: 5, title: 'Ductwork redo was a game-changer', comment: 'The old ducts in our 1940s home were a mess. Tom redesigned the whole system and the difference in air quality and even temperatures is night and day.', createdAt: daysAgo(62) },

  { _id: 'r-21', user: { _id: 'u-21', firstName: 'Patricia', lastName: 'Williams', profilePicture: avatar(28) }, rating: 5, title: 'Storm damage repair', comment: 'After the big storm, Roberto came out the next day, tarped the roof, and worked with our insurance adjuster. Full roof replacement done within 2 weeks. Stress-free experience.', createdAt: daysAgo(7) },
  { _id: 'r-22', user: { _id: 'u-22', firstName: 'Frank', lastName: 'Miller', profilePicture: avatar(54) }, rating: 5, title: 'Metal roof done right', comment: 'Roberto installed a standing seam metal roof on our home. The crew was meticulous, the work is beautiful, and he came in under the original quote. Honest, skilled, professional.', createdAt: daysAgo(25) },
  { _id: 'r-23', user: { _id: 'u-23', firstName: 'Catherine', lastName: 'Moore', profilePicture: avatar(38) }, rating: 5, title: 'Gutter installation perfection', comment: 'New seamless gutters and the difference during the recent rainstorms has been incredible. Roberto even fixed a drainage issue we\'d been living with for years.', createdAt: daysAgo(54) },

  { _id: 'r-24', user: { _id: 'u-24', firstName: 'Hassan', lastName: 'Khan', profilePicture: avatar(29) }, rating: 5, title: 'TV mount over fireplace', comment: 'Marcus mounted a 75" TV over our stone fireplace. Looks incredible, completely hidden cables, and he even installed a new outlet behind it. Quick, clean, professional.', createdAt: daysAgo(6) },
  { _id: 'r-25', user: { _id: 'u-25', firstName: 'Olivia', lastName: 'Reed', profilePicture: avatar(48) }, rating: 5, title: 'Honey-do list savior', comment: 'We had a list of 14 small repairs that had been piling up for months. Marcus knocked them all out in one visit. Fair hourly rate, super efficient, friendly. We now have him on speed dial.', createdAt: daysAgo(18) },
  { _id: 'r-26', user: { _id: 'u-26', firstName: 'Diego', lastName: 'Castro', profilePicture: avatar(64) }, rating: 4, title: 'Drywall repair was seamless', comment: 'Had a doorknob-sized hole in the drywall. Marcus patched it so well you literally cannot tell where it was. Only reason for 4 stars is he arrived 20 minutes late, but called ahead to let us know.', createdAt: daysAgo(31) },

  { _id: 'r-27', user: { _id: 'u-27', firstName: 'Michelle', lastName: 'Stone', profilePicture: avatar(19) }, rating: 5, title: 'Move-out clean perfection', comment: 'Lisa\'s team did our move-out clean and the landlord was so impressed they didn\'t charge us any cleaning fees. Got our full deposit back. Worth every dollar.', createdAt: daysAgo(9) },
  { _id: 'r-28', user: { _id: 'u-28', firstName: 'Brad', lastName: 'Peterson', profilePicture: avatar(65) }, rating: 5, title: 'Weekly clean has changed our lives', comment: 'Lisa and her team have been cleaning our home every other week for 6 months. Same crew every time, they know the house, and the quality is consistently excellent.', createdAt: daysAgo(28) },
  { _id: 'r-29', user: { _id: 'u-29', firstName: 'Anna', lastName: 'Kowalski', profilePicture: avatar(30) }, rating: 4, title: 'Eco-friendly products are a plus', comment: 'We love that Lisa uses non-toxic products because of our kids and pets. The clean is thorough and the team is professional. Lost a star because the price went up a bit between quotes, but Lisa explained the increase before we booked.', createdAt: daysAgo(49) },

  { _id: 'r-30', user: { _id: 'u-30', firstName: 'Henry', lastName: 'Foster', profilePicture: avatar(56) }, rating: 5, title: 'Custom built-ins are a work of art', comment: 'James built floor-to-ceiling bookshelves in our living room and the craftsmanship is beyond what we expected. He is a true artisan. Already planning the next project with him.', createdAt: daysAgo(13) },
  { _id: 'r-31', user: { _id: 'u-31', firstName: 'Julia', lastName: 'Bennett', profilePicture: avatar(35) }, rating: 5, title: 'Crown molding transformed the house', comment: 'James installed crown molding throughout our home. The transformation is incredible. He took so much care with the corner joints and seams - they\'re invisible.', createdAt: daysAgo(36) },
  { _id: 'r-32', user: { _id: 'u-32', firstName: 'Ryan', lastName: 'Hayes', profilePicture: avatar(22) }, rating: 5, title: 'Restoration of historic home', comment: 'We bought a 1908 craftsman that needed extensive trim restoration. James researched the original profiles and matched them perfectly. The home looks like it did when it was built.', createdAt: daysAgo(60) },
];

export const demoPosts: any[] = [
  {
    _id: 'post-1',
    caption: 'Just wrapped up this stunning kitchen remodel in Noe Valley. Custom white oak cabinetry, quartzite countertops, and a show-stopping range hood. Swipe to see the before! 🔨✨',
    images: [img('1556909114-f6e7ad7d3136', 800, 800), img('1600585154340-be6161a56a0c', 800, 800), img('1556909114-1c3a5b1b3e2a', 800, 800)],
    likes: ['u-1', 'u-2', 'u-3', 'u-4', 'u-5', 'u-6', 'u-7'],
    comments: [
      { _id: 'c-1', user: { _id: 'u-1', firstName: 'Megan', lastName: 'Davis', profilePicture: avatar(25) }, userName: 'Megan D.', text: 'Absolutely stunning! 😍', createdAt: hoursAgo(3) },
      { _id: 'c-2', user: { _id: 'u-2', firstName: 'Brian', lastName: 'Hughes', profilePicture: avatar(14) }, userName: 'Brian H.', text: 'That hood! How long did fabrication take?', createdAt: hoursAgo(2) },
    ],
    contractor: { _id: 'contractor-1', user: baseUserBlock({ firstName: 'Sarah', lastName: 'Chen', profilePicture: avatar(47), zipCode: '94110', companyName: 'Cornerstone Construction Co.', userId: 'user-sarah' }), contactInfo: demoContractors[0].contactInfo, slug: 'cornerstone-construction-co', businessName: 'Cornerstone Construction Co.', companyName: 'Cornerstone Construction Co.' },
    createdAt: hoursAgo(8),
    tags: ['Kitchen Remodel', 'Before & After'],
  },
  {
    _id: 'post-2',
    caption: 'Tankless water heater install complete! This Rinnai unit will save the homeowner about 30% on their gas bill and never run out of hot water. 🔥',
    images: [img('1607472586893-edb57bdc0e39', 800, 800), img('1620626011761-bfbe8e303abe', 800, 800)],
    likes: ['u-1', 'u-2', 'u-8'],
    comments: [
      { _id: 'c-3', user: { _id: 'u-8', firstName: 'Chris', lastName: 'Brown', profilePicture: avatar(9) }, userName: 'Chris B.', text: 'How much does a unit like this typically run?', createdAt: hoursAgo(20) },
    ],
    contractor: { _id: 'contractor-2', user: baseUserBlock({ firstName: 'Mike', lastName: 'Rodriguez', profilePicture: avatar(60), zipCode: '94103', companyName: 'RapidFlow Plumbing', userId: 'user-mike' }), contactInfo: demoContractors[1].contactInfo, slug: 'rapidflow-plumbing', businessName: 'RapidFlow Plumbing', companyName: 'RapidFlow Plumbing' },
    createdAt: daysAgo(2),
    tags: ['Water Heater', 'Completed Project'],
  },
  {
    _id: 'post-3',
    caption: 'Just finished a full panel upgrade and dedicated 60A circuit for this Tesla Wall Connector. Clean install, future-proofed for two EVs! ⚡🚗',
    images: [img('1558618666-fcd25c85cd64', 800, 800), img('1565538810643-b5bdb714032a', 800, 800)],
    likes: ['u-9', 'u-10', 'u-11', 'u-12'],
    comments: [],
    contractor: { _id: 'contractor-3', user: baseUserBlock({ firstName: 'Jennifer', lastName: 'Park', profilePicture: avatar(45), zipCode: '94114', companyName: 'Spark Electric Co.', userId: 'user-jennifer' }), contactInfo: demoContractors[2].contactInfo, slug: 'spark-electric-co', businessName: 'Spark Electric Co.', companyName: 'Spark Electric Co.' },
    createdAt: daysAgo(4),
    tags: ['EV Charger', 'Panel Upgrade'],
  },
  {
    _id: 'post-4',
    caption: 'Before & after: this 1890 Victorian got a complete exterior refresh. Five custom colors, all historically accurate. The homeowners couldn\'t be happier. 🎨',
    images: [img('1562259949-e8e7689d7828', 800, 800), img('1556909114-f6e7ad7d3136', 800, 800), img('1600585154340-be6161a56a0c', 800, 800)],
    likes: ['u-13', 'u-14', 'u-15', 'u-16', 'u-17'],
    comments: [
      { _id: 'c-4', user: { _id: 'u-14', firstName: 'Tom', lastName: 'Johnson', profilePicture: avatar(58) }, userName: 'Tom J.', text: 'The color palette is perfect. What brand did you use?', createdAt: daysAgo(3) },
    ],
    contractor: { _id: 'contractor-4', user: baseUserBlock({ firstName: 'David', lastName: 'Kim', profilePicture: avatar(15), zipCode: '94117', companyName: 'Brushwork Painting', userId: 'user-david' }), contactInfo: demoContractors[3].contactInfo, slug: 'brushwork-painting', businessName: 'Brushwork Painting', companyName: 'Brushwork Painting' },
    createdAt: daysAgo(5),
    tags: ['Before & After', 'Exterior Painting'],
  },
  {
    _id: 'post-5',
    caption: 'Drought-tolerant transformation complete! Removed 2,000 sqft of lawn and replaced with California natives, decomposed granite paths, and a drip irrigation system. Beautiful and water-wise. 🌿',
    images: [img('1416879595882-3373a0480b5b', 800, 800), img('1600585154340-be6161a56a0c', 800, 800)],
    likes: ['u-15', 'u-16', 'u-17', 'u-18', 'u-19', 'u-20'],
    comments: [
      { _id: 'c-5', user: { _id: 'u-15', firstName: 'Sophia', lastName: 'Nguyen', profilePicture: avatar(40) }, userName: 'Sophia N.', text: 'This is gorgeous work! How long did the install take?', createdAt: daysAgo(4) },
      { _id: 'c-6', user: { _id: 'u-16', firstName: 'James', lastName: 'King', profilePicture: avatar(63) }, userName: 'James K.', text: 'The plant selection is so thoughtful. Beautiful!', createdAt: daysAgo(3) },
    ],
    contractor: { _id: 'contractor-5', user: baseUserBlock({ firstName: 'Olivia', lastName: 'Martinez', profilePicture: avatar(26), zipCode: '94131', companyName: 'GreenScape Landscaping', userId: 'user-olivia' }), contactInfo: demoContractors[4].contactInfo, slug: 'greenscape-landscaping', businessName: 'GreenScape Landscaping', companyName: 'GreenScape Landscaping' },
    createdAt: daysAgo(6),
    tags: ['Before & After', 'Lawn Care'],
  },
  {
    _id: 'post-6',
    caption: 'Custom floor-to-ceiling walnut library just delivered to a Pacific Heights client. Every shelf, every joint, every detail made by hand in our shop. 📚',
    images: [img('1572297479647-c39e6f0b3e2a', 800, 800), img('1556909114-1c3a5b1b3e2a', 800, 800), img('1600585154340-be6161a56a0c', 800, 800)],
    likes: ['u-30', 'u-31', 'u-32', 'u-1', 'u-2', 'u-3', 'u-4', 'u-5', 'u-6', 'u-7', 'u-8', 'u-9', 'u-10'],
    comments: [
      { _id: 'c-7', user: { _id: 'u-30', firstName: 'Henry', lastName: 'Foster', profilePicture: avatar(56) }, userName: 'Henry F.', text: 'This is the kind of work I aspire to. Master craftsmanship!', createdAt: hoursAgo(15) },
      { _id: 'c-8', user: { _id: 'u-31', firstName: 'Julia', lastName: 'Bennett', profilePicture: avatar(35) }, userName: 'Julia B.', text: '🔥🔥🔥', createdAt: hoursAgo(10) },
    ],
    contractor: { _id: 'contractor-10', user: baseUserBlock({ firstName: 'James', lastName: 'Whitaker', profilePicture: avatar(8), zipCode: '94117', companyName: 'Heritage Woodworks', userId: 'user-james' }), contactInfo: demoContractors[9].contactInfo, slug: 'heritage-woodworks', businessName: 'Heritage Woodworks', companyName: 'Heritage Woodworks' },
    createdAt: daysAgo(1),
    tags: ['Custom Cabinetry', 'Before & After'],
  },
];

export const demoQuotes: any[] = [
  {
    _id: 'quote-1',
    contractor: 'contractor-3',
    contractorId: {
      _id: 'contractor-3',
      companyName: 'Spark Electric Co.',
      businessName: 'Spark Electric Co.',
      profilePicture: avatar(45),
      category: 'electricians',
    },
    user: DEMO_USER_ID,
    projectTitle: 'Tesla Wall Connector Install',
    description: 'Install Tesla Wall Connector in attached garage, including new 60A dedicated circuit and panel upgrade if needed',
    lineItems: [
      { description: 'Tesla Wall Connector (Gen 3)', amount: 47500, quantity: 1, unitPrice: 47500 },
      { description: '60A dedicated circuit installation', amount: 85000, quantity: 1, unitPrice: 85000 },
      { description: 'Panel inspection and minor upgrade', amount: 120000, quantity: 1, unitPrice: 120000 },
      { description: 'Permits and inspection', amount: 35000, quantity: 1, unitPrice: 35000 },
    ],
    subtotal: 287500,
    platformFee: 28750,
    totalAmount: 316250,
    quoteTotal: 316250,
    estimatedStartDate: daysAgo(-7),
    estimatedCompletionDate: daysAgo(-9),
    estimatedDuration: '1-2 days',
    contractorNotes: 'Includes all permits. Your existing 200A panel has capacity, but I recommend a minor subpanel install for future expansion (2 EVs, hot tub, etc). All work inspected and permitted.',
    status: 'accepted',
    jobStatus: 'funded_in_progress',
    jobId: 'job-1',
    isMilestone: true,
    milestones: [
      { _id: 'ms-1', name: 'Equipment procurement', amount: 47500, status: 'released' },
      { _id: 'ms-2', name: 'Electrical rough-in', amount: 205000, status: 'funded' },
      { _id: 'ms-3', name: 'Final install and testing', amount: 63750, status: 'pending' },
    ],
    hasReview: false,
    createdAt: daysAgo(3),
    expiresAt: daysAgo(-11),
  },
  {
    _id: 'quote-2',
    contractor: 'contractor-1',
    contractorId: {
      _id: 'contractor-1',
      companyName: 'Cornerstone Construction Co.',
      businessName: 'Cornerstone Construction Co.',
      profilePicture: avatar(47),
      category: 'builders',
    },
    user: DEMO_USER_ID,
    projectTitle: 'Master Bathroom Remodel',
    description: 'Master bathroom remodel: full gut renovation, new layout, walk-in shower, freestanding tub, custom vanity',
    lineItems: [
      { description: 'Demolition and disposal', amount: 250000, quantity: 1, unitPrice: 250000 },
      { description: 'Plumbing rough-in (relocation)', amount: 380000, quantity: 1, unitPrice: 380000 },
      { description: 'Tile and stonework', amount: 850000, quantity: 1, unitPrice: 850000 },
      { description: 'Custom white oak vanity', amount: 480000, quantity: 1, unitPrice: 480000 },
      { description: 'Freestanding soaker tub', amount: 320000, quantity: 1, unitPrice: 320000 },
      { description: 'Walk-in shower with frameless glass', amount: 520000, quantity: 1, unitPrice: 520000 },
      { description: 'Electrical and lighting', amount: 280000, quantity: 1, unitPrice: 280000 },
      { description: 'Paint and finish work', amount: 120000, quantity: 1, unitPrice: 120000 },
    ],
    subtotal: 3200000,
    platformFee: 320000,
    totalAmount: 3520000,
    quoteTotal: 3520000,
    estimatedStartDate: daysAgo(-21),
    estimatedCompletionDate: daysAgo(-55),
    estimatedDuration: '4-6 weeks',
    contractorNotes: 'This is a comprehensive quote for the full vision. We can phase the work if budget is a concern. Lead time on the custom vanity is 3 weeks, so we recommend confirming within the next 10 days.',
    status: 'pending_user_approval',
    hasReview: false,
    createdAt: daysAgo(1),
    expiresAt: daysAgo(-13),
  },
  {
    _id: 'quote-3',
    contractor: 'contractor-2',
    contractorId: {
      _id: 'contractor-2',
      companyName: 'RapidFlow Plumbing',
      businessName: 'RapidFlow Plumbing',
      profilePicture: avatar(60),
      category: 'plumbers',
    },
    user: DEMO_USER_ID,
    projectTitle: 'Tankless Water Heater Replacement',
    description: 'Replace original 1990s water heater with Rinnai tankless unit, including new gas line',
    lineItems: [
      { description: 'Rinnai RU199iN tankless water heater', amount: 185000, quantity: 1, unitPrice: 185000 },
      { description: 'Gas line upgrade to 3/4"', amount: 145000, quantity: 1, unitPrice: 145000 },
      { description: 'Installation labor', amount: 95000, quantity: 1, unitPrice: 95000 },
      { description: 'Permit', amount: 22000, quantity: 1, unitPrice: 22000 },
    ],
    subtotal: 447000,
    platformFee: 44700,
    totalAmount: 491700,
    quoteTotal: 491700,
    estimatedStartDate: daysAgo(-14),
    estimatedCompletionDate: daysAgo(-15),
    estimatedDuration: '1 day',
    contractorNotes: 'Your existing gas line is undersized for a high-efficiency tankless. This includes the upgrade. We\'ll haul away the old unit and handle the permit.',
    status: 'accepted',
    jobStatus: 'completed_paid',
    jobId: 'job-2',
    hasReview: false,
    createdAt: daysAgo(10),
    expiresAt: daysAgo(-4),
  },
  {
    _id: 'quote-4',
    contractor: 'contractor-8',
    contractorId: {
      _id: 'contractor-8',
      companyName: 'Blue Collar Pro Builders',
      businessName: 'Blue Collar Pro Builders',
      profilePicture: avatar(33),
      category: 'handyman',
    },
    user: DEMO_USER_ID,
    projectTitle: 'TV Mount & Outlet Install',
    description: 'Mount 65" TV over fireplace with hidden cables and add a new outlet behind it',
    lineItems: [
      { description: 'TV mount (full-motion, up to 75")', amount: 35000, quantity: 1, unitPrice: 35000 },
      { description: 'In-wall cable management kit', amount: 15000, quantity: 1, unitPrice: 15000 },
      { description: 'New outlet installation behind TV', amount: 25000, quantity: 1, unitPrice: 25000 },
    ],
    subtotal: 75000,
    platformFee: 7500,
    totalAmount: 82500,
    quoteTotal: 82500,
    estimatedStartDate: daysAgo(-3),
    estimatedDuration: '2 hours',
    contractorNotes: 'Includes cable concealment and a clean outlet install. Can do this week.',
    status: 'pending_user_approval',
    hasReview: false,
    createdAt: hoursAgo(18),
    expiresAt: daysAgo(-12),
  },
  {
    _id: 'quote-5',
    contractor: 'contractor-9',
    contractorId: {
      _id: 'contractor-9',
      companyName: 'Crystal Clean Services',
      businessName: 'Crystal Clean Services',
      profilePicture: avatar(20),
      category: 'cleaners',
    },
    user: DEMO_USER_ID,
    projectTitle: 'Move-Out Deep Clean',
    description: 'Full empty-home deep cleaning for move-out, including appliances, cabinets, and baseboards',
    lineItems: [
      { description: 'Deep cleaning — 2,400 sqft empty home', amount: 45000, quantity: 1, unitPrice: 45000 },
      { description: 'Interior oven and refrigerator cleaning', amount: 12000, quantity: 1, unitPrice: 12000 },
      { description: 'Window interior cleaning (all floors)', amount: 18000, quantity: 1, unitPrice: 18000 },
    ],
    subtotal: 75000,
    platformFee: 7500,
    totalAmount: 82500,
    quoteTotal: 82500,
    estimatedStartDate: daysAgo(-5),
    estimatedDuration: '5-6 hours',
    contractorNotes: 'Eco-friendly products included. Our move-out cleans consistently help clients get their full deposit back.',
    status: 'rejected',
    hasReview: false,
    createdAt: daysAgo(12),
    expiresAt: daysAgo(2),
  },
  {
    _id: 'quote-6',
    contractor: 'contractor-4',
    contractorId: {
      _id: 'contractor-4',
      companyName: 'Brushwork Painting',
      businessName: 'Brushwork Painting',
      profilePicture: avatar(15),
      category: 'painters',
    },
    user: DEMO_USER_ID,
    projectTitle: 'Living Room Repaint',
    description: 'Repaint living room and dining room — color consultation included',
    lineItems: [
      { description: 'Wall prep and priming', amount: 65000, quantity: 1, unitPrice: 65000 },
      { description: 'Paint and finish — 2 coats', amount: 185000, quantity: 1, unitPrice: 185000 },
      { description: 'Trim and door painting', amount: 45000, quantity: 1, unitPrice: 45000 },
    ],
    subtotal: 295000,
    platformFee: 29500,
    totalAmount: 324500,
    quoteTotal: 324500,
    estimatedStartDate: daysAgo(-10),
    estimatedDuration: '3 days',
    contractorNotes: 'Includes Benjamin Moore Regal paint and full color consultation. We\'ll protect all furniture and flooring.',
    status: 'cancelled',
    hasReview: false,
    createdAt: daysAgo(20),
    expiresAt: daysAgo(13),
  },
];

export const demoJobs: any[] = [
  {
    _id: 'job-1',
    quote: 'quote-1',
    contractor: 'contractor-3',
    user: DEMO_USER_ID,
    amountFunded: 316250,
    status: 'funded_in_progress',
    isMilestone: true,
    milestones: [
      { _id: 'ms-1', name: 'Equipment procurement', amount: 47500, status: 'released' },
      { _id: 'ms-2', name: 'Electrical rough-in', amount: 205000, status: 'funded' },
      { _id: 'ms-3', name: 'Final install and testing', amount: 63750, status: 'pending' },
    ],
    startedAt: daysAgo(1),
    createdAt: daysAgo(2),
  },
  {
    _id: 'job-2',
    quote: 'quote-3',
    contractor: 'contractor-2',
    user: DEMO_USER_ID,
    amountFunded: 491700,
    status: 'completed_paid',
    completedDate: daysAgo(2),
    startedAt: daysAgo(8),
    createdAt: daysAgo(8),
  },
];

export const demoConversations: any[] = [
  {
    conversationId: 'conv-1',
    participants: [
      { _id: DEMO_USER_ID, firstName: 'Alex', lastName: 'Morgan', profilePicture: avatar(12) },
      { _id: 'contractor-3', firstName: 'Jennifer', lastName: 'Park', profilePicture: avatar(45), businessName: 'Spark Electric Co.', companyName: 'Spark Electric Co.' },
    ],
    otherParticipant: { _id: 'contractor-3', firstName: 'Jennifer', lastName: 'Park', profilePicture: avatar(45), businessName: 'Spark Electric Co.', companyName: 'Spark Electric Co.' },
    lastMessage: { messageText: 'Great! I\'ll see you Thursday morning at 8am. The crew will have everything wrapped up by lunchtime.', createdAt: hoursAgo(1), senderId: 'contractor-3' },
    unreadCount: 0,
  },
  {
    conversationId: 'conv-2',
    participants: [
      { _id: DEMO_USER_ID, firstName: 'Alex', lastName: 'Morgan', profilePicture: avatar(12) },
      { _id: 'contractor-1', firstName: 'Sarah', lastName: 'Chen', profilePicture: avatar(47), businessName: 'Cornerstone Construction Co.', companyName: 'Cornerstone Construction Co.' },
    ],
    otherParticipant: { _id: 'contractor-1', firstName: 'Sarah', lastName: 'Chen', profilePicture: avatar(47), businessName: 'Cornerstone Construction Co.', companyName: 'Cornerstone Construction Co.' },
    lastMessage: { messageText: 'I\'ve put together the quote for your bathroom remodel. Take a look and let me know if you have any questions!', createdAt: hoursAgo(2), senderId: 'contractor-1' },
    unreadCount: 2,
  },
  {
    conversationId: 'conv-3',
    participants: [
      { _id: DEMO_USER_ID, firstName: 'Alex', lastName: 'Morgan', profilePicture: avatar(12) },
      { _id: 'contractor-2', firstName: 'Mike', lastName: 'Rodriguez', profilePicture: avatar(60), businessName: 'RapidFlow Plumbing', companyName: 'RapidFlow Plumbing' },
    ],
    otherParticipant: { _id: 'contractor-2', firstName: 'Mike', lastName: 'Rodriguez', profilePicture: avatar(60), businessName: 'RapidFlow Plumbing', companyName: 'RapidFlow Plumbing' },
    lastMessage: { messageText: 'Thanks for choosing RapidFlow! It was a pleasure working on your project. Don\'t hesitate to reach out if you have any questions.', createdAt: daysAgo(2), senderId: 'contractor-2' },
    unreadCount: 0,
  },
];

export const demoMessages: Record<string, any[]> = {
  'conv-1': [
    { _id: 'm-1-1', conversationId: 'conv-1', senderId: 'contractor-3', recipientId: DEMO_USER_ID, messageText: 'Hi Alex! I\'m excited to get started on your EV charger install. I have a few quick questions about your panel setup. Is now a good time?', createdAt: hoursAgo(28) },
    { _id: 'm-1-2', conversationId: 'conv-1', senderId: DEMO_USER_ID, recipientId: 'contractor-3', messageText: 'Yes! Now is perfect. What do you need to know?', createdAt: hoursAgo(27) },
    { _id: 'm-1-3', conversationId: 'conv-1', senderId: 'contractor-3', recipientId: DEMO_USER_ID, messageText: 'Can you send me a photo of your existing panel? I want to confirm we have enough spare capacity for a 60A circuit. Also, where would you like the charger mounted in the garage?', createdAt: hoursAgo(27) },
    { _id: 'm-1-4', conversationId: 'conv-1', senderId: DEMO_USER_ID, recipientId: 'contractor-3', messageText: 'Just sent the photo. I\'d like the charger on the left wall, near the driveway entrance.', createdAt: hoursAgo(25) },
    { _id: 'm-1-5', conversationId: 'conv-1', senderId: 'contractor-3', recipientId: DEMO_USER_ID, messageText: 'Perfect. We have plenty of capacity. I\'ve sent over the formal quote with milestones so you can see exactly what\'s happening at each stage. Ready to lock in the schedule?', createdAt: hoursAgo(24) },
    { _id: 'm-1-6', conversationId: 'conv-1', senderId: 'contractor-3', recipientId: DEMO_USER_ID, type: 'quote', messageText: '', quote: { _id: 'quote-msg-1', title: 'Tesla Wall Connector Install', totalAmount: 316250, status: 'accepted', contractor: { companyName: 'Spark Electric Co.', businessName: 'Spark Electric Co.', bannerImage: bannerFor('electricians'), category: 'electricians' }, lineItems: [{ description: 'Tesla Wall Connector (Gen 3)', amount: 47500 }, { description: '60A dedicated circuit installation', amount: 85000 }, { description: 'Panel inspection and minor upgrade', amount: 120000 }, { description: 'Permits and inspection', amount: 35000 }] }, createdAt: hoursAgo(6) },
    { _id: 'm-1-7', conversationId: 'conv-1', senderId: DEMO_USER_ID, recipientId: 'contractor-3', messageText: 'Looks great! Let\'s do it. Can we schedule for next Thursday?', createdAt: hoursAgo(3) },
    { _id: 'm-1-8', conversationId: 'conv-1', senderId: 'contractor-3', recipientId: DEMO_USER_ID, messageText: 'Great! I\'ll see you Thursday morning at 8am. The crew will have everything wrapped up by lunchtime.', createdAt: hoursAgo(1) },
  ],
  'conv-2': [
    { _id: 'm-2-1', conversationId: 'conv-2', senderId: DEMO_USER_ID, recipientId: 'contractor-1', messageText: 'Hi Sarah! We spoke last week about the master bathroom remodel. Any update on the quote?', createdAt: daysAgo(2) },
    { _id: 'm-2-2', conversationId: 'conv-2', senderId: 'contractor-1', recipientId: DEMO_USER_ID, messageText: 'Hi Alex! Yes, I\'ve been finalizing it. I want to walk you through a few options on the tile and vanity before I send the formal quote. Do you have 15 minutes this afternoon?', createdAt: daysAgo(2) },
    { _id: 'm-2-3', conversationId: 'conv-2', senderId: DEMO_USER_ID, recipientId: 'contractor-1', messageText: 'Sure, 3pm works.', createdAt: daysAgo(2) },
    { _id: 'm-2-4', conversationId: 'conv-2', senderId: 'contractor-1', recipientId: DEMO_USER_ID, messageText: 'I\'ve put together the quote for your bathroom remodel. Take a look and let me know if you have any questions!', createdAt: hoursAgo(2) },
    { _id: 'm-2-5', conversationId: 'conv-2', senderId: 'contractor-1', recipientId: DEMO_USER_ID, messageText: 'Also, I want to mention — the custom vanity has a 3-week lead time, so if you want to lock in the schedule for early next month, we should confirm the quote by the end of this week.', createdAt: hoursAgo(2) },
  ],
  'conv-3': [
    { _id: 'm-3-1', conversationId: 'conv-3', senderId: DEMO_USER_ID, recipientId: 'contractor-2', messageText: 'Hi Mike! Our water heater is making some weird noises. Can you take a look?', createdAt: daysAgo(20) },
    { _id: 'm-3-2', conversationId: 'conv-3', senderId: 'contractor-2', recipientId: DEMO_USER_ID, messageText: 'Hi Alex! That sounds like sediment buildup. I can come out tomorrow morning for a free diagnostic. Would 9am work?', createdAt: daysAgo(20) },
    { _id: 'm-3-3', conversationId: 'conv-3', senderId: DEMO_USER_ID, recipientId: 'contractor-2', messageText: '9am is perfect, thanks!', createdAt: daysAgo(20) },
    { _id: 'm-3-4', conversationId: 'conv-3', senderId: 'contractor-2', recipientId: DEMO_USER_ID, messageText: 'Just finished the diagnostic. Unfortunately your unit is on its last legs — it\'s 28 years old! I\'d strongly recommend a full replacement with a tankless unit. I\'ve sent over a quote for your review.', createdAt: daysAgo(10) },
    { _id: 'm-3-5', conversationId: 'conv-3', senderId: DEMO_USER_ID, recipientId: 'contractor-2', messageText: 'Let me look at the quote with my partner and we\'ll get back to you tomorrow.', createdAt: daysAgo(10) },
    { _id: 'm-3-6', conversationId: 'conv-3', senderId: 'contractor-2', recipientId: DEMO_USER_ID, messageText: 'Sounds good! No pressure either way. The quote is valid for 30 days.', createdAt: daysAgo(10) },
    { _id: 'm-3-7', conversationId: 'conv-3', senderId: DEMO_USER_ID, recipientId: 'contractor-2', messageText: 'We\'d like to move forward! How soon can you schedule?', createdAt: daysAgo(9) },
    { _id: 'm-3-8', conversationId: 'conv-3', senderId: 'contractor-2', recipientId: DEMO_USER_ID, messageText: 'I can have it done this Saturday if that works for you. Just need to confirm the deposit.', createdAt: daysAgo(9) },
    { _id: 'm-3-9', conversationId: 'conv-3', senderId: DEMO_USER_ID, recipientId: 'contractor-2', messageText: 'Saturday is perfect. I just paid the deposit through the app.', createdAt: daysAgo(9) },
    { _id: 'm-3-10', conversationId: 'conv-3', senderId: 'contractor-2', recipientId: DEMO_USER_ID, messageText: 'Thanks for choosing RapidFlow! It was a pleasure working on your project. Don\'t hesitate to reach out if you have any questions.', createdAt: daysAgo(2) },
  ],
};

export const demoNotifications: any[] = [
  { _id: 'notif-1', message: 'New message from Spark Electric Co.', type: 'new_message', read: false, createdAt: hoursAgo(1), link: 'messages/conv-1' },
  { _id: 'notif-2', message: 'Sarah Chen at Cornerstone Construction sent you a quote ($35,200)', type: 'new_quote', read: false, createdAt: hoursAgo(2), link: 'quote-review/quote-2' },
  { _id: 'notif-3', message: 'Milestone funded: Electrical rough-in', type: 'job_update', read: false, createdAt: daysAgo(1), link: 'jobs/job-1' },
  { _id: 'notif-4', message: 'Your review of RapidFlow Plumbing was published!', type: 'new_review', read: true, createdAt: daysAgo(2), link: 'contractor-2' },
  { _id: 'notif-5', message: 'Welcome to RateDeed! Complete your profile to get personalized recommendations.', type: 'system', read: true, createdAt: daysAgo(7), link: 'Profile' },
  { _id: 'notif-6', message: 'Spark Electric Co. started your EV charger project', type: 'job_funded', read: true, createdAt: daysAgo(1), link: 'jobs/job-1' },
];

export const demoEarnings = {
  availableBalance: 4250,
  pendingPayouts: 1850,
  totalEarned: 87420,
  totalEarnings: 87420,
  pendingEscrow: 18250,
  pendingAvailableAt: new Date(Date.now() + 86400000 * 2).toISOString(),
  transactions: [
    {
      _id: 'tx-1',
      type: 'payment' as const,
      amount: 2500,
      status: 'completed',
      description: 'Milestone 1 release - Kitchen Plumbing',
      createdAt: daysAgo(1),
      jobTitle: 'Kitchen Plumbing Renovation'
    },
    {
      _id: 'tx-2',
      type: 'payout' as const,
      amount: 3200,
      status: 'completed',
      description: 'Payout to checking account ••••4242',
      createdAt: daysAgo(3)
    },
    {
      _id: 'tx-3',
      type: 'payment' as const,
      amount: 1750,
      status: 'completed',
      description: 'Milestone 2 release - Panel Upgrade',
      createdAt: daysAgo(5),
      jobTitle: '200A Electrical Panel'
    }
  ],
  monthlyEarnings: [
    { month: '2026-01', amount: 12400 },
    { month: '2026-02', amount: 9800 },
    { month: '2026-03', amount: 14200 },
    { month: '2026-04', amount: 11500 },
    { month: '2026-05', amount: 16800 },
    { month: '2026-06', amount: 13200 },
    { month: '2026-07', amount: 9520 },
  ],
  totalJobs: 47,
  completedJobs: 42,
  pendingJobs: 5,
  totalQuotes: 38,
  acceptedQuotes: 29,
  pendingQuotes: 6,
};

export const demoStripeStatus = {
  connected: true,
  accountId: 'acct_demo_12345',
  chargesEnabled: true,
  payoutsEnabled: true,
  detailsSubmitted: true,
  requirements: {
    currentlyDue: [],
    pastDue: [],
    eventuallyDue: [],
    disabledReason: null,
  },
  message: 'Account is in good standing',
};

export const demoContractorJobs: any[] = [
  {
    _id: 'cjob-1',
    quote: 'quote-c1',
    contractor: DEMO_CONTRACTOR_2_ID,
    user: { _id: 'u-job-1', firstName: 'Sarah', lastName: 'Williams', profilePicture: avatar(25) },
    amountFunded: 450000,
    totalAmount: 450000,
    status: 'funded_in_progress',
    startedAt: daysAgo(2),
    createdAt: daysAgo(3),
  },
  {
    _id: 'cjob-2',
    quote: 'quote-c2',
    contractor: DEMO_CONTRACTOR_2_ID,
    user: { _id: 'u-job-2', firstName: 'Robert', lastName: 'Garcia', profilePicture: avatar(14) },
    amountFunded: 85000,
    totalAmount: 85000,
    status: 'completed_pending_release',
    startedAt: daysAgo(5),
    createdAt: daysAgo(5),
  },
  {
    _id: 'cjob-3',
    quote: 'quote-c3',
    contractor: DEMO_CONTRACTOR_2_ID,
    user: { _id: 'u-job-3', firstName: 'Emma', lastName: 'Johnson', profilePicture: avatar(24) },
    amountFunded: 220000,
    totalAmount: 220000,
    status: 'completed_paid',
    completedDate: daysAgo(7),
    startedAt: daysAgo(14),
    createdAt: daysAgo(14),
  },
  {
    _id: 'cjob-4',
    quote: 'quote-c4',
    contractor: DEMO_CONTRACTOR_2_ID,
    user: { _id: 'u-job-4', firstName: 'David', lastName: 'Lee', profilePicture: avatar(9) },
    amountFunded: 180000,
    totalAmount: 180000,
    status: 'awaiting_payment',
    startedAt: daysAgo(1),
    createdAt: daysAgo(1),
  },
];

export const demoContractorQuotes: any[] = [
  {
    _id: 'quote-c1',
    contractor: DEMO_CONTRACTOR_2_ID,
    user: { _id: 'u-job-1', firstName: 'Sarah', lastName: 'Williams', profilePicture: avatar(25) },
    description: 'Drywall repair, paint touch-up, and door adjustment in living room and hallway',
    lineItems: [
      { description: 'Drywall patch and finish (3 holes)', amount: 95000, quantity: 1, unitPrice: 95000 },
      { description: 'Paint touch-up, color match Benjamin Moore', amount: 45000, quantity: 1, unitPrice: 45000 },
      { description: 'Interior door adjustment and hardware tightening', amount: 65000, quantity: 1, unitPrice: 65000 },
      { description: 'Labor and materials', amount: 245000, quantity: 1, unitPrice: 245000 },
    ],
    subtotal: 450000,
    platformFee: 45000,
    totalAmount: 495000,
    estimatedStartDate: daysAgo(-7),
    estimatedCompletionDate: daysAgo(-9),
    estimatedDuration: '2 days',
    contractorNotes: 'Includes color matching and proper texture blending. All work guaranteed for 1 year.',
    status: 'accepted',
    createdAt: daysAgo(5),
  },
  {
    _id: 'quote-c2',
    contractor: DEMO_CONTRACTOR_2_ID,
    user: { _id: 'u-job-2', firstName: 'Robert', lastName: 'Garcia', profilePicture: avatar(14) },
    description: 'TV wall mount with hidden cables and new outlet behind the TV',
    lineItems: [
      { description: 'TV mount (full-motion, up to 75")', amount: 35000, quantity: 1, unitPrice: 35000 },
      { description: 'In-wall cable management kit', amount: 15000, quantity: 1, unitPrice: 15000 },
      { description: 'New outlet installation behind TV', amount: 35000, quantity: 1, unitPrice: 35000 },
    ],
    subtotal: 85000,
    platformFee: 8500,
    totalAmount: 93500,
    estimatedStartDate: daysAgo(-3),
    estimatedCompletionDate: daysAgo(-3),
    estimatedDuration: '2 hours',
    status: 'accepted',
    createdAt: daysAgo(6),
  },
  {
    _id: 'quote-c3',
    contractor: DEMO_CONTRACTOR_2_ID,
    user: { _id: 'u-job-3', firstName: 'Emma', lastName: 'Johnson', profilePicture: avatar(24) },
    description: 'Furniture assembly (IKEA Pax wardrobe system) and TV mounting',
    lineItems: [
      { description: 'IKEA Pax wardrobe assembly (3 units)', amount: 145000, quantity: 1, unitPrice: 145000 },
      { description: 'TV wall mount with cable concealment', amount: 75000, quantity: 1, unitPrice: 75000 },
    ],
    subtotal: 220000,
    platformFee: 22000,
    totalAmount: 242000,
    status: 'accepted',
    createdAt: daysAgo(15),
  },
  {
    _id: 'quote-c4',
    contractor: DEMO_CONTRACTOR_2_ID,
    user: { _id: 'u-job-4', firstName: 'David', lastName: 'Lee', profilePicture: avatar(9) },
    description: 'Bathroom fixture replacement: faucets, showerhead, and towel bars',
    lineItems: [
      { description: 'Kitchen faucet replacement (client-supplied)', amount: 35000, quantity: 1, unitPrice: 35000 },
      { description: 'Bathroom faucet replacement (client-supplied)', amount: 35000, quantity: 1, unitPrice: 35000 },
      { description: 'Showerhead replacement', amount: 25000, quantity: 1, unitPrice: 25000 },
      { description: 'Towel bar and hardware installation (4 pieces)', amount: 45000, quantity: 1, unitPrice: 45000 },
      { description: 'Minor drywall patching around fixtures', amount: 40000, quantity: 1, unitPrice: 40000 },
    ],
    subtotal: 180000,
    platformFee: 18000,
    totalAmount: 198000,
    status: 'pending_user_approval',
    createdAt: daysAgo(1),
  },
];

export const demoContractorProfileData = {
  ...demoContractors[7],
  _id: DEMO_CONTRACTOR_2_ID,
  userId: demoContractorUser._id,
  user: { ...demoContractorUser },
  onboardingComplete: true,
  licenseStatus: 'Verified',
  licenseNumber: 'B-9876543',
  yearsExperience: 6,
  yearsInBusiness: 6,
};
